Repository mobius-network/wallet, pull requests merged in 2018-09, with the labels that each got.

#9 Send funds functionality
  android/app/src/main/AndroidManifest.xml
  package.json
  src/components/App/AppNavigator.js
  src/components/App/Dashboard/Dashboard.js
  src/components/App/Send/AddressForm/AddressForm.js
  src/components/App/Send/AddressForm/AddressFormContainer.js
  src/components/App/Send/AddressForm/Header/Header.js
  src/components/App/Send/AddressForm/Header/index.js
  src/components/App/Send/AddressForm/Header/styles.js
  src/components/App/Send/AddressForm/index.js
  src/components/App/Send/AddressForm/styles.js
  src/components/App/Send/AmountForm/AmountForm.js
  src/components/App/Send/AmountForm/AmountFormContainer.js
  src/components/App/Send/AmountForm/Header/Header.js
  src/components/App/Send/AmountForm/Header/index.js
  src/components/App/Send/AmountForm/Header/styles.js
  src/components/App/Send/AmountForm/index.js
  src/components/App/Send/AmountForm/styles.js
  src/components/App/Send/SendNavigator.js
  src/components/App/Send/Success/Success.js
  src/components/App/Send/Success/SuccessContainer.js
  src/components/App/Send/Success/index.js
  src/components/App/Send/index.js
  src/components/Auth/PinSetup/PinPad/Choose/Confirm/Confirm.js
  src/components/Auth/PinSetup/PinPad/Choose/Setup/Setup.js
  src/components/Auth/PinSetup/PinPad/Header/styles.js
  src/components/Auth/PinSetup/PinPad/Keyboard/Keyboard.js
  src/components/Auth/PinSetup/PinPad/Unlock/Enter/Enter.js
  src/components/shared/BackgroundView/BackgroundView.js
  src/components/shared/DrawerContent/DrawerContent.js
  src/components/shared/DrawerContent/DrawerContentContainer.js
  src/components/shared/DrawerContent/index.js
  src/components/shared/DrawerContent/styles.js
  src/components/shared/Keyboard/Button/Button.js
  src/components/shared/Keyboard/Button/index.js
  src/components/shared/Keyboard/Button/styles.js
  src/components/shared/Keyboard/Keyboard.js
  src/components/shared/Keyboard/index.js
  src/components/shared/Keyboard/styles.js
  src/components/shared/LoadingView/LoadingView.js
  src/components/shared/NavHeader/NavHeader.js
  src/components/shared/SimpleInfo/SimpleInfo.js
  src/components/shared/TextInput/TextInput.js
  src/components/shared/TextInput/index.js
  src/components/shared/TextInput/styles.js
  src/locales/en.json
  src/state/account/selectors.js
  src/state/prices/selectors.js
  src/state/reducer.js
  src/state/saga.js
  src/state/sagas/send/index.js
  src/state/sagas/send/sendStartSaga.js
  src/state/send/actions.js
  src/state/send/index.js
  src/state/send/reducer.js
  src/state/send/selectors.js
  src/state/transfers/reducer.js
  src/state/transfers/selectors.js
  src/state/utils/propSelectors.js
  yarn.lock
Labels: in review

#33 [MOB-481] Shared `Notice` component & better validations for Send screen
  .prettierrc.json
  package.json
  src/components/App/AppNavigator.js
  src/components/App/Send/AddressForm/AddressForm.js
  src/components/App/Send/AddressForm/AddressFormContainer.js
  src/components/App/Send/AddressForm/validate.js
  src/components/App/Send/SendNavigator.js
  src/components/App/Send/Success/Success.js
  src/components/App/Send/Success/SuccessContainer.js
  src/components/App/Send/Success/index.js
  src/components/App/Success/Success.js
  src/components/App/Success/SuccessContainer.js
  src/components/App/Success/index.js
  src/components/shared/Alert/Alert.js
  src/components/shared/BackgroundView/BackgroundView.js
  src/components/shared/BackgroundView/styles.js
  src/components/shared/Notice/Notice.js
  src/components/shared/Notice/NoticeContainer.js
  src/components/shared/Notice/index.js
  src/components/shared/SimpleInfo/SimpleInfo.js
  src/components/shared/TextInput/TextInput.js
  src/locales/en.json
  src/state/app/actions.js
  src/state/app/index.js
  src/state/app/reducer.js
  src/state/app/selectors.js
  src/state/reducer.js
  src/state/sagas/send/sendStartSaga.js
  src/state/send/actions.js
  src/state/send/reducer.js
  src/state/send/selectors.js
  src/utils/validations.js
  templates/component/Component.js.hbs
  templates/component/ComponentContainer.js.hbs
  templates/component/styles.js.hbs
  yarn.lock
Labels: 🌟 Enhancement PR

#32 [MOB-484] Added version to drawer
  android/app/build.gradle
  android/app/src/main/java/network/mobius/wallet/MainApplication.java
  android/settings.gradle
  ios/Podfile
  ios/Podfile.lock
  package.json
  src/components/shared/DrawerContent/DrawerContent.js
  src/components/shared/DrawerContent/styles.js
  src/locales/en.json
  yarn.lock
Labels: 🌟 Enhancement PR, 🔷 Android, 🔷 iOS

#34 [MOB-458] Added three simple events
  src/state/sagas/auth/loginStartSaga.js
  src/state/sagas/auth/signupFinishSaga.js
  src/state/sagas/send/sendStartSaga.js
  src/utils/analytics.js
  src/utils/index.js
Labels: 🌟 Enhancement PR
