Repository mobius-network/wallet, pull requests merged in 2018-10, with the labels that each got.

#31 start fixing android back button problem by preventing it
  android/app/src/main/java/network/mobius/wallet/MainActivity.java
Labels: 🐛 Bug Fix, 🔷 Android

#55 [MOB-548] Fix Recovery screen input keyboard overflow
  src/components/Auth/Recovery/Recovery.js
Labels: in review, 🐛 Bug Fix, 🔷 Android, 🔷 iOS

#54 Trend Feature PR implementation
  src/components/App/Dashboard/Balances/Balances.js
  src/components/App/Dashboard/Balances/BalancesContainer.js
  src/components/shared/AmountItem/AmountItem.js
  src/components/shared/AmountItem/styles.js
  src/state/prices/reducer.js
  src/state/prices/selectors.js
Labels: in review, 🌟 Enhancement PR, 🔷 Android, 🔷 iOS

#47 Adds candlestick graphs to tokens
  ios/MobiusMobileWallet.xcodeproj/project.pbxproj
  ios/MobiusMobileWallet/Info.plist
  package.json
  src/components/App/Dashboard/Balances/Balances.js
  src/components/App/Dashboard/Balances/styles.js
  src/components/shared/AmountItem/AmountItem.js
  src/components/shared/AmountItem/styles.js
  src/components/shared/Chart/Chart.js
  src/components/shared/Chart/ChartContainer.js
  src/components/shared/Chart/index.js
  src/components/shared/Chart/styles.js
  src/components/shared/Styleguide/Styleguide.js
  src/core/services/historical.js
  src/state/history/actions.js
  src/state/history/index.js
  src/state/history/reducer.js
  src/state/prices/reducer.js
  src/state/reducer.js
  src/state/sagas/watchPricesSaga.js
  yarn.lock
Labels: in review, 🌟 Enhancement PR
